Implement the first version of bq2gcs
GlobalFishingWatch/pipe-bq2gcs pull request #1
Opened 2020-06-01 12:54 UTC by smpiano

Related with> https://github.com/GlobalFishingWatch/gfw-eng-tasks/issues/87

2020-06-01 13:18 UTC, enriquetuya requested changes
@smpiano check my comments in the PR.

2020-06-01 13:18 UTC, enriquetuya commented on Dockerfile
> +#GoLang
Remove commented code.

2020-06-01 13:18 UTC, enriquetuya commented on README.md
> +```json
Split examples in 4, and add a brief description for each.

2020-06-01 13:18 UTC, enriquetuya commented on airflow/pipe_bq2gcs_dag.py
> +    return BigQueryCheckOperator(
@smpiano didn't we move this one to airflow-ext?

2020-06-01 13:18 UTC, enriquetuya commented on airflow/pipe_bq2gcs_dag.py
> +# def is_partitioned_table(project_id, dataset_id, table_id):
Remove commented code.

2020-06-01 13:18 UTC, enriquetuya commented on airflow/schemas/bq2gcs_schema.json
> +{
Where is this schema being used?

2020-06-01 13:18 UTC, enriquetuya commented on scripts/bq2gcs.go
> +package main
WOW, a nice surprise. What is your review of doing this in Go?
Let's open a quick discussion in Slack including Raul, Andres, and me to talk about using Go for this purpose. 
Actually, let's talk about this in the next Monday Tech Monthly call.

2020-06-01 13:18 UTC, enriquetuya commented on scripts/bq2gcs.sh
> +TEMPORAL_DATASET="0_ttl24h"
@smpiano should come from the pipe configuration not hardcoded.

2020-06-01 13:18 UTC, enriquetuya commented on scripts/bq2gcs.sh
> +    --append_table
@smpiano why are you doing an append here?

2020-06-01 13:18 UTC, enriquetuya commented on scripts/bq2gcs.sh
> +TEMPORAL_TABLE=${TEMPORAL_DATASET}.${NAME//-/_}
@smpiano Andres is doing a UUID as table name
https://github.com/GlobalFishingWatch/pipe-carrier-portal/blob/master/scripts/publish_vessel_tracks#L53

2020-06-02 15:52 UTC, smpiano commented on README.md
> +```json
Thanks, done!

2020-06-02 15:52 UTC, smpiano commented on airflow/pipe_bq2gcs_dag.py
> +    return BigQueryCheckOperator(
@enriquetuya Not yet, it was pending to move it to `pipe-tools` instead of `airflow-ext`. Do you agree on this or do you rather to be under `airflow-ext`?

2020-06-02 15:52 UTC, smpiano commented on airflow/pipe_bq2gcs_dag.py
> +# def is_partitioned_table(project_id, dataset_id, table_id):
Thanks, done!

2020-06-02 15:52 UTC, smpiano commented on airflow/schemas/bq2gcs_schema.json
> +{
@enriquetuya This schema is used directly in the Airflow Variables values of the key of this project, validates that the structure matches with the requirements.
It is instantiated in the DAG: https://github.com/GlobalFishingWatch/pipe-bq2gcs/pull/1/files#diff-844fa128dd23bab0c5cb938f1d1066bbR146

2020-06-02 15:53 UTC, smpiano commented on scripts/bq2gcs.go
> +package main
@enriquetuya I will move the code to other branch, to see only the differences.

2020-06-02 15:53 UTC, smpiano commented on scripts/bq2gcs.sh
> +    --append_table
It was for a test, I will remove this. Thanks.

2020-06-02 15:53 UTC, smpiano commented on scripts/bq2gcs.sh
> +TEMPORAL_TABLE=${TEMPORAL_DATASET}.${NAME//-/_}
@enriquetuya  here I used the same name in order to be easy to debug and check the data in the temporal dataset. But it would be better to use uuid in case the names came with some complicated chars.

2020-06-02 15:54 UTC, smpiano commented on scripts/bq2gcs.sh
> +TEMPORAL_DATASET="0_ttl24h"
Nice catch, I will use the temp_dataset from config instead.

2020-06-05 20:08 UTC, smpiano commented on airflow/pipe_bq2gcs_dag.py
> +    return BigQueryCheckOperator(
I was wrong, I added in https://github.com/GlobalFishingWatch/airflow-gfw/pull/16

2020-06-05 20:12 UTC, merged